# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

  default:
    image: ubuntu:latest
    before_script:
      - apt install -y python3-pip
      - echo RAPID_API_KEY="$RAPID_API_KEY" >> .env
      - echo RAPID_API_HOST="$RAPID_API_KEY" >> .env
      - echo LLM_SERVER_ADDRESS="$LLM_SERVER_ADDRESS" >> .env
      - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.8/dist-packages/

  stages:
    # - test
    - publicDeploy

  # unit-test:
  #   stage: test
  #   tags: 
  #     - cloud-vm-41-89
  #   script:
  #     - pip install pipenv
  #     - pip install Django

<<<<<<< HEAD
  #     - python3 -m pipenv install
  #     - python3 -m pipenv run python -m unittest discover test/

  publicDeploy:
    stage: publicDeploy    # deploy to heroku
    script:
      - dpl --provider=heroku --app=jammy-jobber --api-key=d9b9ae82-676d-4f77-8e44-a2825b126b9f
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
=======
unit-test:
  image: python:3.12
  stage: test
  script:
<<<<<<< HEAD
<<<<<<< HEAD
    - python3 test_db.py
>>>>>>> 3d200b9 (TRy with os)
=======
=======
    - pip install requests
<<<<<<< HEAD
>>>>>>> bc818d6 (Add installing requests)
=======
    - pip install python-dotenv
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 46d2606 (Add installing python-dotenv)
=======
    - pip install unittest
>>>>>>> 34bc83f (Add tests for new points generation)
=======
>>>>>>> b15d2fe (Remove installing unittest)
    - python3 test/test_db.py
>>>>>>> 5011012 (Change test path)
