# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

<<<<<<< HEAD
=======
before_script:
- echo RAPID_API_KEY="$RAPID_API_KEY" >> .env
- echo RAPID_API_HOST="$RAPID_API_KEY" >> .env

>>>>>>> 4abdc4e (Update .gitlab-ci.yml file to directly set the environment variables in pipeline)

<<<<<<< HEAD
  default:
    image: ubuntu:latest
    before_script:
      - apt install -y python3-pip
      - echo RAPID_API_KEY="$RAPID_API_KEY" >> .env
      - echo RAPID_API_HOST="$RAPID_API_KEY" >> .env
      - echo LLM_SERVER_ADDRESS="$LLM_SERVER_ADDRESS" >> .env
      - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.8/dist-packages/




  stages:
    # - test
    - publicDeploy

  # unit-test:
  #   stage: test
  #   tags: 
  #     - cloud-vm-41-89
  #   script:
  #     - pip install pipenv
  #     - pip install Django

  #     - python3 -m pipenv install
  #     - python3 -m pipenv run python -m unittest discover test/

  publicDeploy:
    stage: publicDeploy    # deploy to heroku
    script:
      - dpl --provider=heroku --app=jammy-jobber --api-key=d9b9ae82-676d-4f77-8e44-a2825b126b9f
    rules:
      - if: $CI_COMMIT_BRANCH == "master"


=======
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
<<<<<<< HEAD

unit-test:
  image: python:3.12
  stage: test
  script:
    - python3 test.py
>>>>>>> a087294 (Try unit testing)
=======
>>>>>>> 0765dc7 (Remove tests)
