# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

  default:
    image: ubuntu:latest
    before_script:
      - apt install -y python3-pip
      - echo RAPID_API_KEY="$RAPID_API_KEY" >> .env
      - echo RAPID_API_HOST="$RAPID_API_KEY" >> .env
      - echo LLM_SERVER_ADDRESS="$LLM_SERVER_ADDRESS" >> .env
      - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.8/dist-packages/

  stages:
    # - test
    - publicDeploy

<<<<<<< HEAD
  # unit-test:
  #   stage: test
  #   tags: 
  #     - cloud-vm-41-89
  #   script:
  #     - pip install pipenv
  #     - pip install Django

  #     - python3 -m pipenv install
  #     - python3 -m pipenv run python -m unittest discover test/

  publicDeploy:
    stage: publicDeploy    # deploy to heroku
    script:
      - dpl --provider=heroku --app=jammy-jobber --api-key=d9b9ae82-676d-4f77-8e44-a2825b126b9f
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
=======
unit-test:
  image: python:3.8
  stage: test
  script:
    - pip install pipenv
<<<<<<< HEAD
<<<<<<< HEAD
    - pipenv shell
    - python3 test/test_semadb.py
    - python3 test/test_sqlite.py
    - python3 test/test_integration.py
>>>>>>> d0bfcb6 (Upgrade pip in pipeline)
=======
    - pipenv run python3 test/test_semadb.py
    - pipenv run python3 test/test_sqlite.py
    - pipenv run python3 test/test_integration.py
>>>>>>> 36b4755 (Add pipenv run)
=======
    - pipenv run python test/test_semadb.py
    - pipenv run python test/test_sqlite.py
    - pipenv run python test/test_integration.py
>>>>>>> cc709d3 (Try running with python)
