# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

image: ubuntu:latest
before_script:
  - apt install -y python3-pip
  - echo RAPID_API_KEY="$RAPID_API_KEY" >> .env
  - echo RAPID_API_HOST="$RAPID_API_KEY" >> .env
  - echo LLM_SERVER_ADDRESS="$LLM_SERVER_ADDRESS" >> .env

stages:
  - test
  - publicDeploy

unit-test:
  stage: test
  tags:
    - cloud-vm-41-89
  script:
    - pip install pipenv
    - python3 -m pipenv install
    - python3 -m pipenv run python -m unittest discover test/

publicDeploy:
  stage: publicDeploy # deploy to heroku
  script:
    - dpl --provider=heroku --app=jammyjobber-simplewebapp --api-key=cb7d9ae7-7c27-458d-b8dd-182c8950619b
