# Generated by Django 4.1 on 2024-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_rename_joblistings_joblisting"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("summary", models.TextField()),
                ("link", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="JobListing",
        ),
    ]
