# Generated by Django 5.0.1 on 2024-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_remove_job_summary_alter_job_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_significant",
            field=models.BooleanField(default=False),
        ),
    ]
